// preview renderer - main component

"use client";

import React, { useMemo, useCallback } from "react";
import type { RenderOutput } from "@/lib/template-engine";
import { SectionRenderer, sectionToMarkdown } from "./SectionRenderer";
import type { PreviewRendererProps, PreviewContext, ResolvedTheme, ExportOptions } from "./types";
import "./preview-theme.css";

// theme helpers

// resolve theme pref
const resolveTheme = (
    preference: "light" | "dark" | "system",
    systemTheme?: "light" | "dark"
): ResolvedTheme => {
    if (preference === "system") {
        return systemTheme ?? "light";
    }
    return preference;
};

// hook for system color scheme
const useSystemTheme = (): ResolvedTheme => {
    const [systemTheme, setSystemTheme] = React.useState<ResolvedTheme>("light");

    React.useEffect(() => {
        // Check initial preference
        const mediaQuery = window.matchMedia("(prefers-color-scheme: dark)");
        setSystemTheme(mediaQuery.matches ? "dark" : "light");

        // Listen for changes
        const handler = (e: MediaQueryListEvent) => {
            setSystemTheme(e.matches ? "dark" : "light");
        };

        mediaQuery.addEventListener("change", handler);
        return () => mediaQuery.removeEventListener("change", handler);
    }, []);

    return systemTheme;
};

// main preview component


export const PreviewRenderer: React.FC<PreviewRendererProps> = ({
    output,
    theme = "system",
    className,
    onThemeChange,
}) => {
    const systemTheme = useSystemTheme();
    const resolvedTheme = resolveTheme(theme, systemTheme);

    // tell parent about theme
    React.useEffect(() => {
        onThemeChange?.(resolvedTheme);
    }, [resolvedTheme, onThemeChange]);

    // context
    const context: PreviewContext = useMemo(
        () => ({
            theme: resolvedTheme,
        }),
        [resolvedTheme]
    );

    // visible sections only
    const visibleSections = useMemo(
        () => output.sections.filter((section) => section.visible),
        [output.sections]
    );

    return (
        <article
            className={`github-preview ${className ?? ""}`}
            data-theme={resolvedTheme}
            role="document"
            aria-label="README Preview"
        >
            {visibleSections.map((section) => (
                <SectionRenderer key={section.id} section={section} context={context} />
            ))}
        </article>
    );
};

// export to markdown

// export IR to markdown string
export const exportToMarkdown = (
    output: RenderOutput,
    options: ExportOptions = {}
): string => {
    const context: PreviewContext = { theme: "light" };
    const lineEnding = options.lineEnding === "crlf" ? "\r\n" : "\n";
    const lines: string[] = [];

    // metadata header optional
    if (options.includeMetadataHeader) {
        lines.push("<!--");
        lines.push(`  Generated by GitHub Profile Studio`);
        lines.push(`  Template: ${output.metadata.templateName} v${output.metadata.templateVersion}`);
        lines.push(`  Generated at: ${new Date().toISOString()}`);
        lines.push("-->");
        lines.push("");
    }

    // render sections
    for (const section of output.sections) {
        if (!section.visible) continue;

        const sectionMd = sectionToMarkdown(section, context, {
            includeSectionComment: options.includeSectionComments,
        });

        if (sectionMd.trim()) {
            lines.push(sectionMd);
        }
    }

    return lines.join(lineEnding);
};

// theme toggle

export interface ThemeToggleProps {
    readonly theme: ResolvedTheme;
    readonly onChange: (theme: ResolvedTheme) => void;
    readonly className?: string;
}

export const ThemeToggle: React.FC<ThemeToggleProps> = ({ theme, onChange, className }) => {
    const toggleTheme = useCallback(() => {
        onChange(theme === "light" ? "dark" : "light");
    }, [theme, onChange]);

    return (
        <button
            onClick={toggleTheme}
            className={className}
            aria-label={`Switch to ${theme === "light" ? "dark" : "light"} theme`}
            title={`Switch to ${theme === "light" ? "dark" : "light"} theme`}
            style={{
                padding: "8px 12px",
                borderRadius: "6px",
                border: "1px solid var(--color-border-default, #d0d7de)",
                background: "var(--color-bg-subtle, #f6f8fa)",
                cursor: "pointer",
                fontSize: "14px",
            }}
        >
            {theme === "light" ? "🌙 Dark" : "☀️ Light"}
        </button>
    );
};

// preview container with controls

export interface PreviewContainerProps extends PreviewRendererProps {
    readonly showThemeToggle?: boolean;
    readonly showExportButton?: boolean;
    readonly onExport?: (markdown: string) => void;
}

export const PreviewContainer: React.FC<PreviewContainerProps> = ({
    output,
    theme: initialTheme = "system",
    className,
    showThemeToggle = true,
    showExportButton = false,
    onExport,
}) => {
    const [theme, setTheme] = React.useState<ResolvedTheme>("light");
    const systemTheme = useSystemTheme();
    const resolvedInitialTheme = resolveTheme(initialTheme, systemTheme);

    React.useEffect(() => {
        setTheme(resolvedInitialTheme);
    }, [resolvedInitialTheme]);

    const handleExport = useCallback(() => {
        const markdown = exportToMarkdown(output, {
            includeMetadataHeader: true,
            includeSectionComments: true,
        });
        onExport?.(markdown);
    }, [output, onExport]);

    return (
        <div className="preview-container">
            {(showThemeToggle || showExportButton) && (
                <div
                    className="preview-controls"
                    style={{
                        display: "flex",
                        gap: "8px",
                        marginBottom: "16px",
                        justifyContent: "flex-end",
                    }}
                >
                    {showThemeToggle && <ThemeToggle theme={theme} onChange={setTheme} />}
                    {showExportButton && (
                        <button
                            onClick={handleExport}
                            style={{
                                padding: "8px 12px",
                                borderRadius: "6px",
                                border: "1px solid var(--color-border-default, #d0d7de)",
                                background: "var(--color-bg-subtle, #f6f8fa)",
                                cursor: "pointer",
                                fontSize: "14px",
                            }}
                        >
                            📋 Export Markdown
                        </button>
                    )}
                </div>
            )}
            <PreviewRenderer output={output} theme={theme} className={className} />
        </div>
    );
};

export default PreviewRenderer;
